// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDA9f0a06bD3AdwVX2u2UTX7ZcZS06Kwvk',
    appId: '1:167935050380:web:73bd2dcc78bea608c171a9',
    messagingSenderId: '167935050380',
    projectId: 'anasapp-eaba4',
    authDomain: 'anasapp-eaba4.firebaseapp.com',
    storageBucket: 'anasapp-eaba4.appspot.com',
    measurementId: 'G-PCDW4GTH2D',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyB0damJ1W5Df2PxWhd9hOL-lldO9fHuLno',
    appId: '1:167935050380:android:1e72699b4a9d0dbdc171a9',
    messagingSenderId: '167935050380',
    projectId: 'anasapp-eaba4',
    storageBucket: 'anasapp-eaba4.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAbcejVC17iyIow1iq173hb66eTGhnFBeQ',
    appId: '1:167935050380:ios:cebc578b5bef642ac171a9',
    messagingSenderId: '167935050380',
    projectId: 'anasapp-eaba4',
    storageBucket: 'anasapp-eaba4.appspot.com',
    iosBundleId: 'com.example.criptoApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAbcejVC17iyIow1iq173hb66eTGhnFBeQ',
    appId: '1:167935050380:ios:32066e89efe3bccac171a9',
    messagingSenderId: '167935050380',
    projectId: 'anasapp-eaba4',
    storageBucket: 'anasapp-eaba4.appspot.com',
    iosBundleId: 'com.example.criptoApp.RunnerTests',
  );
}
